FROM golang:latest

RUN apt update && apt upgrade -y && \
    apt install -y bash git openssh-server

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

RUN go mod download

COPY . .

RUN go build

CMD ["./backend"]