FROM golang:latest

RUN apt update && apt upgrade -y && \
    apt install -y bash git openssh-server

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

RUN git config --global url."https://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@github.com".insteadOf "https://github.com"

RUN go mod download

COPY . .

RUN go build

CMD ["./backend"]