// Code generated by entc, DO NOT EDIT.

package unit

const (
	// Label holds the string label denoting the unit type in the database.
	Label = "unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldContentName holds the string denoting the content_name field in the database.
	FieldContentName = "content_name"
	// EdgeContents holds the string denoting the contents edge name in mutations.
	EdgeContents = "contents"
	// Table holds the table name of the unit in the database.
	Table = "units"
	// ContentsTable is the table that holds the contents relation/edge.
	ContentsTable = "books"
	// ContentsInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	ContentsInverseTable = "books"
	// ContentsColumn is the table column denoting the contents relation/edge.
	ContentsColumn = "unit_contents"
)

// Columns holds all SQL columns for unit fields.
var Columns = []string{
	FieldID,
	FieldContent,
	FieldContentName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultContentName holds the default value on creation for the "content_name" field.
	DefaultContentName string
)
