// Code generated by entc, DO NOT EDIT.

package unit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/backand/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContent), v))
	})
}

// ContentName applies equality check predicate on the "content_name" field. It's identical to ContentNameEQ.
func ContentName(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContentName), v))
	})
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContent), v))
	})
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldContent), v))
	})
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Unit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldContent), v...))
	})
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Unit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldContent), v...))
	})
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldContent), v))
	})
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldContent), v))
	})
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldContent), v))
	})
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldContent), v))
	})
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldContent), v))
	})
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldContent), v))
	})
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldContent), v))
	})
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldContent), v))
	})
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldContent), v))
	})
}

// ContentNameEQ applies the EQ predicate on the "content_name" field.
func ContentNameEQ(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContentName), v))
	})
}

// ContentNameNEQ applies the NEQ predicate on the "content_name" field.
func ContentNameNEQ(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldContentName), v))
	})
}

// ContentNameIn applies the In predicate on the "content_name" field.
func ContentNameIn(vs ...string) predicate.Unit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldContentName), v...))
	})
}

// ContentNameNotIn applies the NotIn predicate on the "content_name" field.
func ContentNameNotIn(vs ...string) predicate.Unit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Unit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldContentName), v...))
	})
}

// ContentNameGT applies the GT predicate on the "content_name" field.
func ContentNameGT(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldContentName), v))
	})
}

// ContentNameGTE applies the GTE predicate on the "content_name" field.
func ContentNameGTE(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldContentName), v))
	})
}

// ContentNameLT applies the LT predicate on the "content_name" field.
func ContentNameLT(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldContentName), v))
	})
}

// ContentNameLTE applies the LTE predicate on the "content_name" field.
func ContentNameLTE(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldContentName), v))
	})
}

// ContentNameContains applies the Contains predicate on the "content_name" field.
func ContentNameContains(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldContentName), v))
	})
}

// ContentNameHasPrefix applies the HasPrefix predicate on the "content_name" field.
func ContentNameHasPrefix(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldContentName), v))
	})
}

// ContentNameHasSuffix applies the HasSuffix predicate on the "content_name" field.
func ContentNameHasSuffix(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldContentName), v))
	})
}

// ContentNameEqualFold applies the EqualFold predicate on the "content_name" field.
func ContentNameEqualFold(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldContentName), v))
	})
}

// ContentNameContainsFold applies the ContainsFold predicate on the "content_name" field.
func ContentNameContainsFold(v string) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldContentName), v))
	})
}

// HasContents applies the HasEdge predicate on the "contents" edge.
func HasContents() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ContentsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContentsTable, ContentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentsWith applies the HasEdge predicate on the "contents" edge with a given conditions (other predicates).
func HasContentsWith(preds ...predicate.Book) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ContentsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContentsTable, ContentsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Unit) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		p(s.Not())
	})
}
